default_platform(:ios)

platform :ios do
  desc "Deploy to App Store"
  lane :deploy do
    ensure_fastlane_version(version: ">= 2.0.0")

    match(type: "appstore")
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(scheme: "Runner", xcodeproj: "Runner.xcodeproj")

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  desc "Deploy to TestFlight"
  lane :deploy_testflight do
    match(type: "adhoc")
    build_app(scheme: "Runner", xcodeproj: "Runner.xcodeproj")

    upload_to_testflight(
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  desc "Run tests"
  lane :test do
    scan(scheme: "Runner")
  end
end