default_platform(:android)

platform :android do
  desc "Deploy to Google Play Store"
  lane :deploy do
    ensure_fastlane_version(version: ">= 4.0.0")

    gradle(task: "clean")
    gradle(task: "bundle")

    upload_to_play_store(
      track: "production",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Deploy to staging track"
  lane :deploy_staging do
    gradle(task: "clean")
    gradle(task: "bundle")

    upload_to_play_store(
      track: "internal",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Run tests"
  lane :test do
    gradle(task: "test")
  end
end